name: "JFrog FrogBot SCA Repro"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read
  security-events: write

env:
  BUILD_NAME: "jfrog-frogbot-repro"
  BUILD_NUMBER: ${{ github.run_number }}
  # Ensure you have this secret set in your repo
  JF_URL: ${{ secrets.JF_URL }}

jobs:
  build-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Setup JFrog CLI (OIDC)
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ env.JF_URL }}
        with:
          oidc-provider-name: kamalkn24/test@github

      - name: Configure pip to use Artifactory Virtual Repo
        run: |
          jf pip-config --repo-resolve=sws-jf-example-python-remote
          
      - name: Install Python Dependencies
        run: |
          jf pip install --upgrade pip
          jf pip install -r requirements.txt \
            --build-name $BUILD_NAME \
            --build-number $BUILD_NUMBER

      - name: Enable FrogBot (OIDC)
        uses: jfrog/frogbot@v2.29.4
        env:
          JF_URL: ${{ env.JF_URL }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JFROG_CLI_LOG_LEVEL: "DEBUG"
          JF_USE_CONFIG_PROFILE: "true"
        with:
          oidc-provider-name: kamalkn24/test@github

      - name: Install build module
        run: python -m pip install --upgrade build

      - name: Debug Resolved Dependencies
        run: pip freeze

      - name: Build Package
        run: python -m build

      - name: Publish Build Info
        run: |
          jf rt bce $BUILD_NAME $BUILD_NUMBER
          jf rt upload "dist/*" "sws-jf-example-python-local" \
            --build-name $BUILD_NAME \
            --build-number $BUILD_NUMBER
          jf rt bp $BUILD_NAME $BUILD_NUMBER

      - name: Scan Published Build
        run: jf build-scan --format=sarif $BUILD_NAME $BUILD_NUMBER

      - name: Audit Workspace Dependencies
        run: jf audit --format=sarif > audit-results.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: audit-results.sarif
